development:
  adapter: postgresql
  database: score-tracker_dev
  host: localhost

test:
  adapter: postgresql
  database: score-tracker_test
  host: localhost

production:
  adapter: postgresql
  database: score-tracker_production
  host: localhost
